### ISSUE TITLE
Impossibile attivare la programmazione giornaliera

### ISSUE THREAD

**Issue by gnoto** [DanRobo76/VMC-HELTY-FLOW#7]
<img width="346" alt="Screenshot 2024-01-03 at 11 03 50" src="https://github.com/DanRobo76/VMC-HELTY-FLOW/assets/54668134/bbce6752-8da6-4136-8793-61da18ad2797">

Ho attivato la programmazione giornaliera, inserendo i relativi slot di accensione e spegnimento, ma la programmazione risulta sempre disabilitata (vedi screenshot) e non funzionante.

Grazie
Giampiero

**Comment by gnoto** [comment]
Grazie @DanRobo76  
immagino che la mancata attivazione dipenda dal fatto che le fasce orarie da me scelte non rispettano i criteri imposti.
Il mio obiettivo sarebbe quello di mantenere una fascia diurna (es: 8.00 - 20.59), con la VMC attiva a una certa velocità e una fascia notturna (es: 21.00 - 7.59) con velocità, appunto, "notturna". Per via del passaggio della mezzanotte però, queste fasce non sono corrette.
E' questo il problema?

Grazie

**Comment by DanRobo76** [comment]
La tua impostazione non rispetta i criteri 😅 dovrai trovare una via di mezzo
Buona ventilazione 😉
